<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>{</string>
	<key>foldingStopMarker</key>
	<string>}</string>
	<key>name</key>
	<string>Puppet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#puppet.strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.define</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.resource</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#puppet.reference</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.puppet</string>
		</dict>
		<key>puppet.class</key>
		<dict>
			<key>begin</key>
			<string>^\s*(class)\s+([a-zA-Z0-9_:]+)\s*((?=\())?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>class.puppet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>name.class.puppet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((inherits)\s+([a-zA-Z0-9_:]+)\s*)?{</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>inherits.puppet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>name.inherits.puppet</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)(?=(\s*(inherits|{)))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>puppet.comments</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.puppet</string>
		</dict>
		<key>puppet.constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(false|true|running|stopped|present|latest|absent|file|directory|undef)\b</string>
					<key>name</key>
					<string>constant.puppet</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\w+\s*(?=(=&gt;|\+&gt;|-&gt;|==))\s*</string>
					<key>name</key>
					<string>attribute.puppet</string>
				</dict>
			</array>
		</dict>
		<key>puppet.define</key>
		<dict>
			<key>begin</key>
			<string>^\s*(define)\s+([a-zA-Z0-9_:]+)(\s*(?=\())?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>define.puppet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>name.define.puppet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\s){</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)(?=\s*{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>puppet.functions</key>
		<dict>
			<key>begin</key>
			<string>\b(alert|create_resources|crit|debug|defined|emerg|err|extlookup|fail|file|fqdn_rand|generate|include|info|inline_template|md5|notice|realize|regsubst|require|search|sha1|shellquote|split|sprintf|tag|tagged|template|versioncmp|warning)\b\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>function.puppet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\()</string>
					<key>end</key>
					<string>(?=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>puppet.keywords</key>
		<dict>
			<key>match</key>
			<string>\b(case|if|else|in|and)(?!::)</string>
			<key>name</key>
			<string>keyword.puppet</string>
		</dict>
		<key>puppet.reference</key>
		<dict>
			<key>begin</key>
			<string>([A-Z][a-z0-9_]+)\s*\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>reference.puppet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\[)</string>
					<key>end</key>
					<string>(?=\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>puppet.resource</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9_:]+)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>resource.puppet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>:</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;={)</string>
					<key>end</key>
					<string>(?=:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>puppet.strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.puppet</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#puppet.variables</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.puppet</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>puppet.variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$)([a-zA-Zx7f-xff\$]|::)([a-zA-Z0-9_x7f-xff\$]|::)*\b</string>
					<key>name</key>
					<string>variable.puppet</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\$\{)(?:[a-zA-Zx7f-xff\$]|::)(?:[a-zA-Z0-9_x7f-xff\$]|::)*(\})</string>
					<key>name</key>
					<string>variable.puppet</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.puppet</string>
	<key>uuid</key>
	<string>5500AB50-AFC8-4689-8913-0E632D0C0DB5</string>
</dict>
</plist>
